from pmp_manip.opcode_info.data_imports import *

class ExtensionDropdownType(DropdownType):
    pass

class ExtensionInputType(InputType):
    pass

extension = OpcodeInfoGroup(
    name="gceTestRunner",
    opcode_info=DualKeyDict({
        ("gceTestRunner_describe", "&gceTestRunner::describe (NAME) {SUBSTACK}"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("NAME", "NAME"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("SUBSTACK", "SUBSTACK"): InputInfo(type=BuiltinInputType.SCRIPT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_runTest", "&gceTestRunner::test (NAME) {SUBSTACK}"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("NAME", "NAME"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("SUBSTACK", "SUBSTACK"): InputInfo(type=BuiltinInputType.SCRIPT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_assert", "&gceTestRunner::assert <CONDITION>"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("CONDITION", "CONDITION"): InputInfo(type=BuiltinInputType.BOOLEAN, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_assertNot", "&gceTestRunner::assert not <CONDITION>"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("CONDITION", "CONDITION"): InputInfo(type=BuiltinInputType.BOOLEAN, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_assertMsg", "&gceTestRunner::assert <CONDITION> message (MSG)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("CONDITION", "CONDITION"): InputInfo(type=BuiltinInputType.BOOLEAN, menu=None),
                ("MSG", "MSG"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_assertEqual", "&gceTestRunner::assert (A) = (B)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("A", "A"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("B", "B"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_assertThrows", "&gceTestRunner::assert throws (MSG) {SUBSTACK}"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("MSG", "MSG"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("SUBSTACK", "SUBSTACK"): InputInfo(type=BuiltinInputType.SCRIPT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_assertDoesNotThrow", "&gceTestRunner::assert does not throw {SUBSTACK}"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SUBSTACK", "SUBSTACK"): InputInfo(type=BuiltinInputType.SCRIPT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_fail", "&gceTestRunner::fail (MSG)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("MSG", "MSG"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_reportResults", "&gceTestRunner::report results"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_resetResults", "&gceTestRunner::reset results"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_getPassed", "&gceTestRunner::passed"): OpcodeInfo(
            opcode_type=OpcodeType.STRING_REPORTER,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
        ("gceTestRunner_getFailed", "&gceTestRunner::failed"): OpcodeInfo(
            opcode_type=OpcodeType.STRING_REPORTER,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
            allow_embedded=False,
        ),
    }),
)